FeatureScript 3044;
import(path : "onshape/std/common.fs", version : "3044.0");

export function convertProfilePoints(data is array, units is ValueWithUnits) returns array
{
    const length = size(data);
    var points = makeArray(length);
    for (var i, point in data)
    {
        points[i] = vector(point[0], point[1]) * units;
    }

    return points;
}

export function transformRot(linear is Matrix)
{
    return transform(linear, vector(0, 0, 0) * meter);
}

export const UP_COORD_SYSTEM = coordSystem(WORLD_ORIGIN, X_DIRECTION, -Y_DIRECTION);

export function transformToCoordSystem(transform is Transform) returns CoordSystem
{
    return coordSystem(
        transform.translation,
        transform.linear * vector(1, 0, 0),
        transform.linear * vector(0, 0, 1)
    );
}

/** A 3D rotation matrix from Euler angles in XYZ order (R = Rz * Ry * Rx).
 *  `angles` is a Vector of 3 radians, [x, y, z].  Generated by Claude Sonnet 4.6. */
export function rotationMatrix3dEulerXYZ(angles is Vector) returns Matrix
precondition
{
    @size(angles) == 3;
}
{
    const cx = cos(angles[0]);
    const sx = sin(angles[0]);
    const cy = cos(angles[1]);
    const sy = sin(angles[1]);
    const cz = cos(angles[2]);
    const sz = sin(angles[2]);

    // R = Rz * Ry * Rx
    return matrix([
                [cy * cz, cz * sx * sy - cx * sz, cx * cz * sy + sx * sz],
                [cy * sz, cx * cz + sx * sy * sz, cx * sy * sz - cz * sx],
                [-sy, cy * sx, cx * cy]
            ]);
}
